server:
  port: 8082

spring:
  application:
    name: ms-gestion-personal

  datasource:
    url: jdbc:mysql://localhost:3306/Hotel_CL_CB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "" # Tu clave de MySQL si le configuraste una
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "CAMBIA_ESTO_POR_UNA_CLAVE_LARGA_Y_SECRETA_DE_AL_MENOS_32_CARACTERES"
  expiration-ms: 3600000