server:
  port: 8086

spring:
  application:
    name: ms-log-auditoria
  datasource:
    url: jdbc:mysql://localhost:3306/Hotel_CL_CB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ""  # Si en tu Mac le pusiste contraseña al root de MySQL, escríbela aquí
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true