server:
  port: 8083

spring:
  application:
    name: ms-gestion-huespedes

  # MySQL DataSource
  datasource:
    url: jdbc:mysql://hotel-mysql:3306/Hotel_CL_CB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  # JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Swagger / OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
